chore: update justfile

diff --git a/package/justfile b/package/justfile
--- a/package/justfile
+++ b/package/justfile
@@ -6,19 +6,12 @@ get_value_from_toml key:
 
 get_local_package_dir:
   #!/bin/bash
-  if [[ "$OSTYPE" == "linux-gnu"* ]]; then
+  if [[ "$OSTYPE" == "darwin"* ]]; then
+    # macOS
+    echo "$HOME/Library/Application Support/typst/packages"
+  elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
     # Linux
     echo "${XDG_DATA_HOME:-$HOME/.local/share}/typst/packages"
-  elif [[ "$OSTYPE" == "darwin"* ]]; then
-    # macOS
-    DIR1="$HOME/.local/share/typst/packages"
-    DIR2="$HOME/Library/Application Support/typst/packages"
-    if [ -d "$DIR1" ]; then
-      echo "$DIR1"
-    else
-      mkdir -p "$DIR2"
-      echo "$DIR2"
-    fi
   elif [[ "$OSTYPE" == "msys"* || "$OSTYPE" == "cygwin"* ]]; then
     # Windows
     echo "$APPDATA/typst/packages"
@@ -33,20 +26,34 @@ install:
     echo "Error: Typst is not installed. Please install it before running this recipe."
     exit 1
   fi
+
   PACKAGE_NAME=$(just get_value_from_toml name)
   PACKAGE_VERSION=$(just get_value_from_toml version)
   LOCAL_PACKAGE_DIR=$(just get_local_package_dir)
   TARGET_DIR="$LOCAL_PACKAGE_DIR/local/$PACKAGE_NAME/$PACKAGE_VERSION"
+
   mkdir -p "$TARGET_DIR"
-  cp -r ./* "$TARGET_DIR"
-  echo "Package $PACKAGE_NAME version $PACKAGE_VERSION has been installed to $TARGET_DIR"
+
+  echo "Copying files to $TARGET_DIR..."
+  
+  cp {{TOML_FILE}} "$TARGET_DIR"
+
+  cp *.typ "$TARGET_DIR"
+  
+  if [ -f "calabi_yau.wasm" ]; then
+    cp calabi_yau.wasm "$TARGET_DIR"
+  else
+    echo "Warning: calabi_yau.wasm not found in current directory."
+    exit 1
+  fi
+
+  [ -f "README.md" ] && cp README.md "$TARGET_DIR"
+  [ -f "LICENSE" ] && cp LICENSE "$TARGET_DIR"
+
+  echo "Package $PACKAGE_NAME version $PACKAGE_VERSION has been installed."
 
 clean:
   #!/bin/bash
-  if ! command -v typst &> /dev/null; then
-    echo "Error: Typst is not installed. Please install it before running this recipe."
-    exit 1
-  fi
   PACKAGE_NAME=$(just get_value_from_toml name)
   PACKAGE_VERSION=$(just get_value_from_toml version)
   LOCAL_PACKAGE_DIR=$(just get_local_package_dir)
